### ISSUE TITLE
Deduplicate blind and original submissions

### ISSUE THREAD

**Issue by carlosmondra** [openreview/openreview-expertise#112]
Previously, the expertise CLI was used by the Super User who has access to all data, including the original notes that usually reply to invitations ending with `/-/Submission`. Since the expertise and the matching are now services, we need to get the notes that reply to the `/-/Blind_Submission` invitations. However, the Super User will get duplicates (original and blind submission).

In order to deduplicate the Notes, we can take advantage of the `original` field value in the Blind Notes.

**Comment by melisabok** [comment]
That means if a publication is found and contains an "original" value then remove the "original" note if the it is presents in the same list of publications.
