### ISSUE TITLE
A few errors installing the software and downloading data

### ISSUE THREAD

**Issue by neubig** [openreview/openreview-expertise#60]
Hello,

I'm trying to follow the installation directions but running into an issue on the pip install. For reference, this was done on a clean AWS instance with the Ubuntu 18.04 Deep Learning AMI installed.

    # Download from the appropriate places to the current directory
    # * config.json
    # * multifacet_recommender_data.tar.gz
    
    # Install conda packages
    conda create -n affinity python=3.7
    conda activate affinity
    conda install -y pip
    conda install -y pytorch torchvision torchaudio cudatoolkit=10.0 -c pytorch
    conda install -y intel-openmp==2019.4
    conda install -y faiss-gpu -c pytorch
    
    # Get repo
    git clone git@github.com:openreview/openreview-expertise.git
    cd openreview-expertise
    
    # Install pip packages
    pip install `pwd`

Upon doing this it installs a bunch of things but gets the following error (error 1).

    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/envs/affinity/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8pglcmv_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8pglcmv_/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-h8n1te74
         cwd: /tmp/pip-req-build-8pglcmv_/
    Complete output (40 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/expertise
    copying expertise/core.py -> build/lib/expertise
    copying expertise/tfidf_scores.py -> build/lib/expertise
    copying expertise/run_ranking.py -> build/lib/expertise
    copying expertise/infer_model.py -> build/lib/expertise
    copying expertise/run.py -> build/lib/expertise
    copying expertise/run_duplicate_detection.py -> build/lib/expertise
    copying expertise/__init__.py -> build/lib/expertise
    copying expertise/create_dataset.py -> build/lib/expertise
    installing to build/bdist.linux-x86_64/wheel
    running install
    /home/ubuntu/anaconda3/envs/affinity/bin/python: No module named spacy
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8pglcmv_/setup.py", line 54, in <module>
        zip_safe=False
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 335, in run
        self.run_command('install')
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-8pglcmv_/setup.py", line 16, in run
        check_call('python -m spacy download en'.split())
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['python', '-m', 'spacy', 'download', 'en']' returned non-zero exit status 1.
    ----------------------------------------
    ERROR: Failed building wheel for openreview-expertise

This was resolved by running "pip install pwd" one more time, as it seems the first run installed spacy, just too late to build the wheel.

Then I followed with the following commands. Note that in the last command "openreview.net" was changed into "api.openreview.net", so the URL should probably be fixed in the README (error 2).

    # Get specter
    git clone https://github.com/allenai/specter.git
    cd specter
    
    wget https://ai2-s2-research-public.s3-us-west-2.amazonaws.com/specter/archive.tar.gz
    tar -xzvf archive.tar.gz
    
    pip install -y -r requirements.txt
    python setup.py install
    conda install -y filelock
    cd ..
    
    # Unzip the recommender
    tar -xzf ../multifacet_recommender_data.tar.gz
    
    # Create data for this venue
    python -m expertise.create_dataset ../config.json --baseurl https://api.openreview.net --password <your_password> --username <your_username>

However, I ran into the following error (error 3). I haven't had time to debug yet, but just from the stack trace it seems that this might be due to a change in the OpenReview API where it's now returning a list instead of a different datatype? I wonder if it'd be possible to get some help on this?

    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/home/ubuntu/work/openreview-expertise/expertise/create_dataset.py", line 376, in <module>
        expertise.run()
      File "/home/ubuntu/work/openreview-expertise/expertise/create_dataset.py", line 340, in run
        expertise = self.retrieve_expertise()
      File "/home/ubuntu/work/openreview-expertise/expertise/create_dataset.py", line 243, in retrieve_expertise
        valid_members, invalid_members = self.get_profile_ids(group_ids=group_ids, reviewer_ids=reviewer_ids)
      File "/home/ubuntu/work/openreview-expertise/expertise/create_dataset.py", line 185, in get_profile_ids
        email_profiles.append((profile.id, email))
    AttributeError: 'list' object has no attribute 'id'

Thanks a lot in advance!

**Comment by melisabok** [comment]
error 3 should be fixed: this [PR](https://github.com/openreview/openreview-expertise/pull/58) was fixing it and it was pending for review, I merged it, please pull the changes and try again.

**Comment by melisabok** [comment]
error 2 is fixed: the README file was updated.

**Comment by melisabok** [comment]
Hi @neubig , I assigned the issue to @ameyagodbole  that can check what is happening. 

How I usually run the model is:

1. Create a folder inside of the expertise cloned repo called 'acl_arr_may'
2. cd acl_arr_may
3. copy the config file and paste it inside the folder
4. run `python -m expertise.create_dataset config.json`
5. run `python -m expertise.run config.json`

TFIDF could be outdated, have you tried the ELMo model?

**Comment by melisabok** [comment]
This error `TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.` is the same error that we are getting in our tests so I'm guessing something has changed in library. We will investigate the issue.

**Comment by neubig** [comment]
Thanks a lot @melisabok ! II tried out both ELMo and BM25. ELMo got the same error as specter (error 4). BM25 got a new error (error 7):

    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/multiprocessing/pool.py", line 121, in worker
        result = (True, func(*args, **kwds))
      File "/home/ubuntu/anaconda3/envs/affinity/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/home/ubuntu/work/openreview-expertise/expertise/models/bm25/bm25.py", line 97, in all_scores_helper
        reviewer_scores = self.score(submission)
      File "/home/ubuntu/work/openreview-expertise/expertise/models/bm25/bm25.py", line 91, in score
        reviewer_scores[profile_id] = submission_scores[start_index:end_index].max().item()
    RuntimeError: invalid argument 1: cannot perform reduction function max on tensor with no elements because the operation does not have an identity at /opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:370

**Comment by melisabok** [comment]
We are investigation the issue but if this helps, my virtualenv where I run SPECTER+MFR has the library 'allennlp' mapped locally:

```
allennlp                      0.9.0     /home/mbok/specter/src/allennlp
```

It seems to be a very old version based on the latest one: https://pypi.org/project/allennlp/#history

**Comment by neubig** [comment]
Thanks a lot! I'm working on https://github.com/openreview/openreview-expertise/issues/62 at the moment, and I think I'll get back to this in the afternoon.

**Comment by melisabok** [comment]
Tests are fixed now through #61 , it seems to be an issue with a new version of the library, you can pull the changes from master and try again. ELMo should be working now but we are still investigating the issue with SPECTER+MFR.

**Comment by neubig** [comment]
Great, thanks a bunch! I tested ELMo and it ran all the way through, so it seems like the issues are mostly fixed. However, looking at the recommendations they don't seem to be all that good. I think one part of the reason for this is because many of our reviewers don't have many papers loaded into their OR profiles (I'm working on a fix for this), but it might also be because the ELMo model is not very good as well. If you can figure out the issue with specter+MFR that would also be appreciated!

**Comment by melisabok** [comment]
ELMo doesn't perform as better as SPECTER+MFR. 

When you create the dataset these is an output file called 'metadata.json' that contains the list of reviewers with no profile or publications. You can ask them to signup in OpenReview and upload their publications from DBLP. This is the hardest part of the process, having all profiles complete.

Ameya is working on the issue now. As a workaround, I can run the SPECTER+MFR scores for you.

**Comment by melisabok** [comment]
@neubig , could you pull the changes from master and check if error 4 is still happening? or you are getting another error?

Thanks,

Melisa

**Comment by neubig** [comment]
Thanks! Specter+MFR seems to be running as well (the run has started successfully). I'll close the issue, as I think the major things I reported here have been resolved. I'll re-open a different more focused issue if I have any additional problems.
