### ISSUE TITLE
Example of previously-used script for csv_expertise?

### ISSUE THREAD

**Issue by neubig** [openreview/openreview-expertise#62]
Hello,

From my understanding of the code here:
* https://github.com/openreview/openreview-expertise/blob/785d9e7d01ac8765886530439d8501780c314189/expertise/create_dataset.py#L215
* https://github.com/openreview/openreview-expertise/blob/master/expertise/create_dataset.py#L267

By default, the "expertise" code is only based on papers from openreview, but you can add extra papers as expertise from other sources through a csv file. I had two questions:
1. Is there a good example of an existing script to generate the `csv_expertise` csv file from other sources?
2. If not, I'd be willing to create one (e.g. using semantic scholar's API), would it be helpful to send out a PR?

Thanks!

**Comment by melisabok** [comment]
There is no existing script to create the files from external sources but I can give you an example of it looks the jsonl file created by the create_dataset function. 

When you run a `create_dataset` function, a directory called `archives` is created and one jsonl file is created per reviewer. The name of the file is the reviewer profile id but it can be whatever you want, an email address for example. The model will output the scores file using the file name to represent the reviewer. 

The jsonl must have one json record per row and the mandatory fields are 'title' and 'abstract'. This format follows the schema of an OpenReview note but it is very easy to build it from another sources:


Paper entry for a reviewer:
```
{"id": "S14pwaZdWS", "content": {"title": "Hierarchical Learning of Curves Application to Guidewire Localization in Fluoroscopy",  "abstract": "In this paper we present a method for learning a curve model for detection and segmentation by closely integrating a hierarchical curve representation using generative and discriminative models with a hierarchical inference algorithm. We apply this method to the problem of automatic localization of the guidewire in fluoroscopic sequences. In fluoroscopic sequences, the guidewire appears as a hardly visible, non-rigid one-dimensional curve. Our paper has three main contributions. Firstly, we present a novel method to learn the complex shape and appearance of a free-form curve using a hierarchical model of curves of increasing degrees of complexity and a database of manual annotations. Secondly, we present a novel computational paradigm in the context of Marginal Space Learning, in which the algorithm is closely integrated with the hierarchical representation to obtain fast parameter inference. Thirdly, to our knowledge this is the first full system which robustly localizes the whole guidewire and has extensive validation on hundreds of frames. We present very good quantitative and qualitative results on real fluoroscopic video sequences, obtained in just one second per frame."}}
```

Code example to create the jsonl file using external data:

```
        with open(f'/path/{profile.id}.jsonl', 'w', encoding='utf-8') as f:
            for paper in publications:
                f.write(json.dumps({
                        'id': paper.id,
                        'content': {
                            'title': paper.content['title'],
                            'abstract': paper.content.get('abstract')
                        }
                    }) + '\n')  
```

profile.id is the reviewer identifier.
publications can be the list of publications from Semantic Scholar for example. You need paper id, title and abstract.

If you want to build the expertise with the union of OpenReview and Semantic Scholar publications then you can create the dataset first and then append the Semantic Scholar publications to each file.

**Comment by neubig** [comment]
OK, great, thanks! I was just wondering if something like this already was available (presumably something does exists _somewhere_, given that the `csv_expertise` command line flag exists). Anyway, I'll try to do this with semantic scholar, and contribute it if it seems to be worth contributing.

**Comment by melisabok** [comment]
You are right!, it exists this parameter and it is available in the README file:

```
csv_expertise: (optinal) String with the relative path from dataset.directory to a csv file containing the expertise in the following format: "author id","publication_id","title","abstract". This can be added instead of or on top of match_group and reviewer_ids, the values will be combined.
```

I'm sorry I'm not too familiar with all the options. I aways use the expertise from OpenReview. Feel free to try this out and let me know the issue that may find.

**Comment by neubig** [comment]
I'm not sure if this will be useful, but here's a script that I came up with to grab papers from semantic scholar: https://gist.github.com/neubig/246f9021049b23910dbe4e01ba5da86b

I'll close this issue as I have what I want now.

By the way, it might be nice on the main OpenReview site to have an option to import papers from Semantic Scholar as there is from DBLP.
