### ISSUE TITLE
Reviewers with no papers in OpenReview skipped despite having csv_expertise

### ISSUE THREAD

**Issue by neubig** [openreview/openreview-expertise#87]
Hello,

In the ARR workflow, we are importing papers both from OpenReview/DBLP and from Semantic Scholar. For the latter, we are adding papers via the `csv_expertise` command. However, it seems that the expertise code skips any reviewers that don't have any papers in OpenReview/DBLP, even if they have an entry in `csv_expertise`. This is a bit inconvenient for us, as it causes us to skip several hundred reviewers in our pool, even though they've filled in their semantic scholar profiles. I wonder if this check could be made to not skip reviewers if they have any papers imported through `csv_expertise`?

It would be great if this could be fixed by December 16th when we run paper assignment and I'll try to do so, but I'm not super-familiar with the code and don't have a huge amount of time between now and then so I thought I'd post an issue here in case it's a quick fix for someone else.

Thanks so much as always!

**Comment by melisabok** [comment]
Here is where the expertise is being retrieved for the members of the match_group: https://github.com/openreview/openreview-expertise/blob/master/expertise/create_dataset.py#L240

It seems that is taking in account both expertises: from OpenReview API and `csv_expertise`. Is it possible that the reviewer doesn't have an OpenReview profile? could you share an example so it is easy to debug?

**Comment by purujitgoyal** [comment]
Can I get a sample file for `csv_expertise.csv`? There's no test that tests for this right now.

**Comment by neubig** [comment]
Sure! I will send this via email.
